#!/usr/bin/env lua

local git_root = require('scripts.common').git_root

local deps = {
  'busted',
  'LuaCov',
}

local cmd = string.format('luarocks --lua-version 5.4 --tree %s/.luarocks install %%s', git_root)

for _, dep in ipairs(deps) do
  os.execute(string.format(cmd, dep))
end

-- vim:ft=lua
